package arqSw.Hibernate;
// Generated 20/03/2017 08:42:47 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Camiseta generated by hbm2java
 */
public class Camiseta  implements java.io.Serializable {


     private Integer idCamiseta;
     private String talla;
     private String color;
     private String material;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Camiseta() {
    }

    public Camiseta(String talla, String color, String material, Set<Venta> ventas) {
       this.talla = talla;
       this.color = color;
       this.material = material;
       this.ventas = ventas;
    }
   
    public Integer getIdCamiseta() {
        return this.idCamiseta;
    }
    
    public void setIdCamiseta(Integer idCamiseta) {
        this.idCamiseta = idCamiseta;
    }
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


