package arqSw.Hibernate;
// Generated 20/03/2017 08:42:47 PM by Hibernate Tools 3.6.0



/**
 * EstampasventasId generated by hbm2java
 */
public class EstampasventasId  implements java.io.Serializable {


     private int idVenta;
     private int idEstampa;

    public EstampasventasId() {
    }

    public EstampasventasId(int idVenta, int idEstampa) {
       this.idVenta = idVenta;
       this.idEstampa = idEstampa;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public int getIdEstampa() {
        return this.idEstampa;
    }
    
    public void setIdEstampa(int idEstampa) {
        this.idEstampa = idEstampa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstampasventasId) ) return false;
		 EstampasventasId castOther = ( EstampasventasId ) other; 
         
		 return (this.getIdVenta()==castOther.getIdVenta())
 && (this.getIdEstampa()==castOther.getIdEstampa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVenta();
         result = 37 * result + this.getIdEstampa();
         return result;
   }   


}


