package arqSw.Hibernate;
// Generated 20/03/2017 08:42:47 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Cliente cliente;
     private Camiseta camiseta;
     private String fecha;
     private Set<Estampasventas> estampasventases = new HashSet<Estampasventas>(0);

    public Venta() {
    }

	
    public Venta(Cliente cliente, Camiseta camiseta) {
        this.cliente = cliente;
        this.camiseta = camiseta;
    }
    public Venta(Cliente cliente, Camiseta camiseta, String fecha, Set<Estampasventas> estampasventases) {
       this.cliente = cliente;
       this.camiseta = camiseta;
       this.fecha = fecha;
       this.estampasventases = estampasventases;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Camiseta getCamiseta() {
        return this.camiseta;
    }
    
    public void setCamiseta(Camiseta camiseta) {
        this.camiseta = camiseta;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public Set<Estampasventas> getEstampasventases() {
        return this.estampasventases;
    }
    
    public void setEstampasventases(Set<Estampasventas> estampasventases) {
        this.estampasventases = estampasventases;
    }




}


